# Generated by Django 6.0.3 on 2026-04-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoreranna_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Picked Up', 'Picked Up'), ('Handed Over', 'Handed Over'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Handed Over', 'Handed Over'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
