# Generated by Django 6.0.3 on 2026-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoreranna_app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
